### ISSUE TITLE
PHP class extends find

### ISSUE THREAD

**Issue by lixiaobu** [rafaelstz/brackets-magento-hint#11]
Yes! Thank you for all the things you do for us.
I still have an idea about PHP class find,just like this , if we put our mouse on a PHP class and click it ,it can alert this PHP extends father class beside,and we can easy open this father class file and check it.that is all .could you finish it? or tell me how to write a plugin?I a students,poor at English......

**Comment by lixiaobu** [comment]
Brackets codeintel,this plugin a little like what I want....

**Comment by rafaelstz** [comment]
Hi @lixiaobu , I am very happy with your incentive and initiative, my english is poor too. I studied this tutorials to learn more about how to create a brackets extension. :smile: 

http://brackets.io/docs
https://github.com/adobe/brackets/wiki/How-to-Write-Extensions
http://code.tutsplus.com/tutorials/creating-brackets-extensions--net-36781
http://www.adobe.com/devnet/edge-code/articles/building-your-first-brackets-extension.html
http://artoale.com/tutorial/brackets/2013/09/30/writing-brackets-extension-01/

**Comment by lixiaobu** [comment]
haha, you from Brazil,chat with me in China....Thank you for you help!
